/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cricBuzz;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
       //why we write app object
        App classUnderTest = new App();
        assertNotNull("Greeting", "app should have a greeting");
    }
}
